[project]
name = "sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lap>=0.5.12",
    "opencv-python>=4.11.0.86",
    "ultralytics>=8.3.241",
    "tqdm>=4.66.1", # Added tqdm for progress bar
    "pandas>=2.2.0", # Added pandas for data manipulation
    "docling>=2.66.0",
    "ollama>=0.6.2",
    "google-generativeai>=0.8.6",
    "requests>=2.32.5",
    "clip",
    "pychonet>=2.7.3",
]

[tool.uv.sources]
clip = { git = "https://github.com/ultralytics/CLIP.git" }
